create extension if not exists "pgcrypto";

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  name text not null unique,
  email text,
  company text,
  notes text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  name text not null,
  rate numeric(12, 2) not null,
  description text,
  active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.invoices (
  id bigint generated by default as identity primary key,
  invoice_number text not null unique,
  client_id bigint not null references public.clients(id) on delete restrict,
  generated_at timestamptz not null default timezone('utc', now()),
  detail_level text not null check (detail_level in ('summary', 'project', 'detailed')),
  subtotal numeric(12, 2) not null default 0,
  pdf_path text not null,
  summary_pdf_path text,
  project_pdf_path text,
  detailed_pdf_path text,
  status text not null default 'unpaid' check (status in ('paid', 'unpaid')),
  paid_at timestamptz
);

create table if not exists public.time_entries (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  start_at timestamptz not null,
  end_at timestamptz not null,
  hours numeric(8, 2) not null,
  description text not null,
  invoiced boolean not null default false,
  invoice_id bigint references public.invoices(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  check (end_at > start_at)
);

create table if not exists public.settings (
  key text primary key,
  value text not null
);

insert into public.settings(key, value)
values
  ('business_name', 'HourMint'),
  ('invoice_prefix', 'HM'),
  ('default_detail_level', 'project'),
  ('company_logo_path', '')
on conflict (key) do nothing;

alter table public.clients enable row level security;
alter table public.projects enable row level security;
alter table public.invoices enable row level security;
alter table public.time_entries enable row level security;
alter table public.settings enable row level security;

create policy "Authenticated users can read clients"
on public.clients
for select
to authenticated
using (true);

create policy "Authenticated users can mutate clients"
on public.clients
for all
to authenticated
using (true)
with check (true);

create policy "Authenticated users can read projects"
on public.projects
for select
to authenticated
using (true);

create policy "Authenticated users can mutate projects"
on public.projects
for all
to authenticated
using (true)
with check (true);

create policy "Authenticated users can read invoices"
on public.invoices
for select
to authenticated
using (true);

create policy "Authenticated users can mutate invoices"
on public.invoices
for all
to authenticated
using (true)
with check (true);

create policy "Authenticated users can read time entries"
on public.time_entries
for select
to authenticated
using (true);

create policy "Authenticated users can mutate time entries"
on public.time_entries
for all
to authenticated
using (true)
with check (true);

create policy "Authenticated users can read settings"
on public.settings
for select
to authenticated
using (true);

create policy "Authenticated users can mutate settings"
on public.settings
for all
to authenticated
using (true)
with check (true);

insert into storage.buckets (id, name, public)
values ('branding', 'branding', true)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('invoices', 'invoices', false)
on conflict (id) do nothing;

create policy "Authenticated users can read branding assets"
on storage.objects
for select
to authenticated
using (bucket_id = 'branding');

create policy "Authenticated users can manage branding assets"
on storage.objects
for all
to authenticated
using (bucket_id = 'branding')
with check (bucket_id = 'branding');

create policy "Authenticated users can read invoice assets"
on storage.objects
for select
to authenticated
using (bucket_id = 'invoices');

create policy "Authenticated users can manage invoice assets"
on storage.objects
for all
to authenticated
using (bucket_id = 'invoices')
with check (bucket_id = 'invoices');

create or replace function public.reset_hourmint_sequences()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  perform setval(pg_get_serial_sequence('public.clients', 'id'), greatest((select coalesce(max(id), 1) from public.clients), 1), true);
  perform setval(pg_get_serial_sequence('public.projects', 'id'), greatest((select coalesce(max(id), 1) from public.projects), 1), true);
  perform setval(pg_get_serial_sequence('public.invoices', 'id'), greatest((select coalesce(max(id), 1) from public.invoices), 1), true);
  perform setval(pg_get_serial_sequence('public.time_entries', 'id'), greatest((select coalesce(max(id), 1) from public.time_entries), 1), true);
end;
$$;

grant execute on function public.reset_hourmint_sequences() to authenticated, service_role;
