create table public.invoice_line_items (
  id bigint generated by default as identity primary key,
  invoice_id bigint not null references public.invoices(id) on delete cascade,
  description text not null check (char_length(btrim(description)) > 0),
  amount numeric(12, 2) not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create index invoice_line_items_invoice_id_sort_order_idx
on public.invoice_line_items (invoice_id, sort_order);

alter table public.invoice_line_items enable row level security;

create policy "Authenticated users can read invoice line items"
on public.invoice_line_items
for select
to authenticated
using (true);

create policy "Authenticated users can mutate invoice line items"
on public.invoice_line_items
for all
to authenticated
using (true)
with check (true);
